In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,20,(5,6))

In [3]:
arr

array([[14, 15, 19, 16,  2,  7],
       [ 9, 17, 14, 12,  4, 19],
       [11, 12,  1,  6, 18,  5],
       [12,  3, 19,  2, 14, 10],
       [ 8,  9,  3,  3,  1, 10]])

In [4]:
arr1=np.random.randint(20,40,(5,6))

In [5]:
arr1

array([[28, 31, 28, 36, 32, 38],
       [33, 33, 25, 31, 21, 27],
       [23, 33, 28, 31, 38, 25],
       [22, 36, 25, 27, 22, 23],
       [24, 27, 32, 35, 34, 26]])

In [6]:
arr.T

array([[14,  9, 11, 12,  8],
       [15, 17, 12,  3,  9],
       [19, 14,  1, 19,  3],
       [16, 12,  6,  2,  3],
       [ 2,  4, 18, 14,  1],
       [ 7, 19,  5, 10, 10]])

In [7]:
arr.flatten()

array([14, 15, 19, 16,  2,  7,  9, 17, 14, 12,  4, 19, 11, 12,  1,  6, 18,
        5, 12,  3, 19,  2, 14, 10,  8,  9,  3,  3,  1, 10])

In [12]:
np.expand_dims(arr,axis=1)

array([[[14, 15, 19, 16,  2,  7]],

       [[ 9, 17, 14, 12,  4, 19]],

       [[11, 12,  1,  6, 18,  5]],

       [[12,  3, 19,  2, 14, 10]],

       [[ 8,  9,  3,  3,  1, 10]]])

In [14]:
data=np.array([[1],[2],[3]])

In [15]:
np.squeeze(data)

array([1, 2, 3])

In [16]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [17]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [18]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
arr

array([[14, 15, 19, 16,  2,  7],
       [ 9, 17, 14, 12,  4, 19],
       [11, 12,  1,  6, 18,  5],
       [12,  3, 19,  2, 14, 10],
       [ 8,  9,  3,  3,  1, 10]])

In [20]:
arr1

array([[28, 31, 28, 36, 32, 38],
       [33, 33, 25, 31, 21, 27],
       [23, 33, 28, 31, 38, 25],
       [22, 36, 25, 27, 22, 23],
       [24, 27, 32, 35, 34, 26]])

In [21]:
arr+arr1

array([[42, 46, 47, 52, 34, 45],
       [42, 50, 39, 43, 25, 46],
       [34, 45, 29, 37, 56, 30],
       [34, 39, 44, 29, 36, 33],
       [32, 36, 35, 38, 35, 36]])

In [22]:
arr-arr1


array([[-14, -16,  -9, -20, -30, -31],
       [-24, -16, -11, -19, -17,  -8],
       [-12, -21, -27, -25, -20, -20],
       [-10, -33,  -6, -25,  -8, -13],
       [-16, -18, -29, -32, -33, -16]])

In [24]:
arr*arr1

array([[392, 465, 532, 576,  64, 266],
       [297, 561, 350, 372,  84, 513],
       [253, 396,  28, 186, 684, 125],
       [264, 108, 475,  54, 308, 230],
       [192, 243,  96, 105,  34, 260]])

In [25]:
arr**arr1

array([[ 2339663274187948032, -8207802330756800273, -6131528708192907151,
                           0,           4294967296,  4767239791123969681],
       [ 4810798710570394889,  -589027242450939375, -7441037181604331520,
        -4611686018427387904,        4398046511104,  2589931763838723563],
       [ 6839173302027254275,                    0,                    1,
        -6507783832580653056, -7943720547152560128,   298023223876953125],
       [ 5729018530666381312,   150094635296999121,  4554986577074761267,
                   134217728,  7049268766814765056,   200376420520689664],
       [                   0, -8127490854706933095,     1853020188851841,
           50031545098999707,                    1, -2537764290115403776]])

In [23]:
arr/arr1

array([[0.5       , 0.48387097, 0.67857143, 0.44444444, 0.0625    ,
        0.18421053],
       [0.27272727, 0.51515152, 0.56      , 0.38709677, 0.19047619,
        0.7037037 ],
       [0.47826087, 0.36363636, 0.03571429, 0.19354839, 0.47368421,
        0.2       ],
       [0.54545455, 0.08333333, 0.76      , 0.07407407, 0.63636364,
        0.43478261],
       [0.33333333, 0.33333333, 0.09375   , 0.08571429, 0.02941176,
        0.38461538]])

In [26]:
arr>arr1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [27]:
arr<arr1

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [29]:
arr2=np.array(["himanshi","kawade"])

In [30]:
arr2

array(['himanshi', 'kawade'], dtype='<U8')

In [31]:
np.char.upper(arr2)

array(['HIMANSHI', 'KAWADE'], dtype='<U8')

In [32]:
np.char.capitalize(arr2)

array(['Himanshi', 'Kawade'], dtype='<U8')

In [33]:
np.char.title(arr2)

array(['Himanshi', 'Kawade'], dtype='<U8')

In [34]:
arr

array([[14, 15, 19, 16,  2,  7],
       [ 9, 17, 14, 12,  4, 19],
       [11, 12,  1,  6, 18,  5],
       [12,  3, 19,  2, 14, 10],
       [ 8,  9,  3,  3,  1, 10]])

In [35]:
np.sin(arr)

array([[ 0.99060736,  0.65028784,  0.14987721, -0.28790332,  0.90929743,
         0.6569866 ],
       [ 0.41211849, -0.96139749,  0.99060736, -0.53657292, -0.7568025 ,
         0.14987721],
       [-0.99999021, -0.53657292,  0.84147098, -0.2794155 , -0.75098725,
        -0.95892427],
       [-0.53657292,  0.14112001,  0.14987721,  0.90929743,  0.99060736,
        -0.54402111],
       [ 0.98935825,  0.41211849,  0.14112001,  0.14112001,  0.84147098,
        -0.54402111]])

In [36]:
np.cos(arr)

array([[ 0.13673722, -0.75968791,  0.98870462, -0.95765948, -0.41614684,
         0.75390225],
       [-0.91113026, -0.27516334,  0.13673722,  0.84385396, -0.65364362,
         0.98870462],
       [ 0.0044257 ,  0.84385396,  0.54030231,  0.96017029,  0.66031671,
         0.28366219],
       [ 0.84385396, -0.9899925 ,  0.98870462, -0.41614684,  0.13673722,
        -0.83907153],
       [-0.14550003, -0.91113026, -0.9899925 , -0.9899925 ,  0.54030231,
        -0.83907153]])

In [37]:
np.tan(arr)

array([[ 7.24460662e+00, -8.55993401e-01,  1.51589471e-01,
         3.00632242e-01, -2.18503986e+00,  8.71447983e-01],
       [-4.52315659e-01,  3.49391565e+00,  7.24460662e+00,
        -6.35859929e-01,  1.15782128e+00,  1.51589471e-01],
       [-2.25950846e+02, -6.35859929e-01,  1.55740772e+00,
        -2.91006191e-01, -1.13731371e+00, -3.38051501e+00],
       [-6.35859929e-01, -1.42546543e-01,  1.51589471e-01,
        -2.18503986e+00,  7.24460662e+00,  6.48360827e-01],
       [-6.79971146e+00, -4.52315659e-01, -1.42546543e-01,
        -1.42546543e-01,  1.55740772e+00,  6.48360827e-01]])

In [38]:
np.log10(arr)

array([[1.14612804, 1.17609126, 1.2787536 , 1.20411998, 0.30103   ,
        0.84509804],
       [0.95424251, 1.23044892, 1.14612804, 1.07918125, 0.60205999,
        1.2787536 ],
       [1.04139269, 1.07918125, 0.        , 0.77815125, 1.25527251,
        0.69897   ],
       [1.07918125, 0.47712125, 1.2787536 , 0.30103   , 1.14612804,
        1.        ],
       [0.90308999, 0.95424251, 0.47712125, 0.47712125, 0.        ,
        1.        ]])

In [39]:
np.exp(arr)

array([[1.20260428e+06, 3.26901737e+06, 1.78482301e+08, 8.88611052e+06,
        7.38905610e+00, 1.09663316e+03],
       [8.10308393e+03, 2.41549528e+07, 1.20260428e+06, 1.62754791e+05,
        5.45981500e+01, 1.78482301e+08],
       [5.98741417e+04, 1.62754791e+05, 2.71828183e+00, 4.03428793e+02,
        6.56599691e+07, 1.48413159e+02],
       [1.62754791e+05, 2.00855369e+01, 1.78482301e+08, 7.38905610e+00,
        1.20260428e+06, 2.20264658e+04],
       [2.98095799e+03, 8.10308393e+03, 2.00855369e+01, 2.00855369e+01,
        2.71828183e+00, 2.20264658e+04]])

In [41]:
np.power(arr,3)

array([[2744, 3375, 6859, 4096,    8,  343],
       [ 729, 4913, 2744, 1728,   64, 6859],
       [1331, 1728,    1,  216, 5832,  125],
       [1728,   27, 6859,    8, 2744, 1000],
       [ 512,  729,   27,   27,    1, 1000]])

In [44]:
np.min(arr)

1

In [45]:
np.max(arr)

19

In [46]:
np.std(arr)

5.791276965306433

In [47]:
np.var(arr)

33.53888888888889

In [49]:
np.median(arr)

10.0

In [51]:
np.subtract(arr,arr1)

array([[-14, -16,  -9, -20, -30, -31],
       [-24, -16, -11, -19, -17,  -8],
       [-12, -21, -27, -25, -20, -20],
       [-10, -33,  -6, -25,  -8, -13],
       [-16, -18, -29, -32, -33, -16]])

In [52]:
np.multiply(arr,arr1)

array([[392, 465, 532, 576,  64, 266],
       [297, 561, 350, 372,  84, 513],
       [253, 396,  28, 186, 684, 125],
       [264, 108, 475,  54, 308, 230],
       [192, 243,  96, 105,  34, 260]])

In [53]:
np.mod(arr,arr1)

array([[14, 15, 19, 16,  2,  7],
       [ 9, 17, 14, 12,  4, 19],
       [11, 12,  1,  6, 18,  5],
       [12,  3, 19,  2, 14, 10],
       [ 8,  9,  3,  3,  1, 10]])

In [54]:
np.power(arr,arr1)

array([[ 2339663274187948032, -8207802330756800273, -6131528708192907151,
                           0,           4294967296,  4767239791123969681],
       [ 4810798710570394889,  -589027242450939375, -7441037181604331520,
        -4611686018427387904,        4398046511104,  2589931763838723563],
       [ 6839173302027254275,                    0,                    1,
        -6507783832580653056, -7943720547152560128,   298023223876953125],
       [ 5729018530666381312,   150094635296999121,  4554986577074761267,
                   134217728,  7049268766814765056,   200376420520689664],
       [                   0, -8127490854706933095,     1853020188851841,
           50031545098999707,                    1, -2537764290115403776]])

In [55]:
np.sqrt(arr)

array([[3.74165739, 3.87298335, 4.35889894, 4.        , 1.41421356,
        2.64575131],
       [3.        , 4.12310563, 3.74165739, 3.46410162, 2.        ,
        4.35889894],
       [3.31662479, 3.46410162, 1.        , 2.44948974, 4.24264069,
        2.23606798],
       [3.46410162, 1.73205081, 4.35889894, 1.41421356, 3.74165739,
        3.16227766],
       [2.82842712, 3.        , 1.73205081, 1.73205081, 1.        ,
        3.16227766]])