In [1]:
import numpy as np

In [2]:
arr=np.array([2,3,4,5,61,56,15,21,98,32,10])

In [3]:
arr

array([ 2,  3,  4,  5, 61, 56, 15, 21, 98, 32, 10])

In [4]:
np.sort(arr)

array([ 2,  3,  4,  5, 10, 15, 21, 32, 56, 61, 98])

In [6]:
np.searchsorted(arr,3)

1

In [7]:
arr1=np.array([0,356,125,458,478,599,0,10,20,30,40])

In [8]:
np.count_nonzero(arr1)

9

In [11]:
np.where(arr1>2)

(array([ 1,  2,  3,  4,  5,  7,  8,  9, 10]),)

In [16]:
np.extract(arr1>2,arr1)

array([356, 125, 458, 478, 599,  10,  20,  30,  40])

In [18]:
arr1.byteswap()

array([                   0,  7206040878769504256,  9007199254740992000,
       -3890828603071397888, -2449676722312839168,  6269573631253151744,
                          0,   720575940379279360,  1441151880758558720,
        2161727821137838080,  2882303761517117440])

In [19]:
a=np.copy(arr1)

In [20]:
a

array([  0, 356, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [21]:
arr1

array([  0, 356, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [22]:
b=arr1.view()

In [23]:
b

array([  0, 356, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [24]:
b[0]=234

In [25]:
b

array([234, 356, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [26]:
arr1

array([234, 356, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [27]:
b=arr1

In [28]:
a[1]=45

In [29]:
a

array([  0,  45, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [30]:
arr1

array([234, 356, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [31]:
import numpy.matlib as nm

In [32]:
nm.ones(4)

matrix([[1., 1., 1., 1.]])

In [33]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [36]:
arr1

array([234, 356, 125, 458, 478, 599,   0,  10,  20,  30,  40])

In [37]:
arr2=np.array([10,20,30,40,50,60,70,80,90,10,110])

In [38]:
arr2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90,  10, 110])

In [39]:
np.dot(arr1,arr2)

98670

In [40]:
arr3=np.random.randint([[2,3],[4,5]])

In [41]:
arr4=np.random.randint([[5,3],[2,5]])

In [42]:
arr3

array([[1, 1],
       [3, 2]])

In [43]:
arr4

array([[0, 1],
       [0, 2]])

In [44]:
np.dot(arr3,arr4)

array([[0, 3],
       [0, 7]])

In [45]:
arr3@arr4

array([[0, 3],
       [0, 7]])