In [1]:
import numpy as np


In [2]:
range(5)

range(0, 5)

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(.4,10.12,0.1)

array([ 0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,
        1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,
        2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,
        3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,
        4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,
        5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,
        7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,
        8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,
        9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1])

In [5]:
list(np.arange(.4,10.12,0.1))

[0.4,
 0.5,
 0.6,
 0.7,
 0.7999999999999999,
 0.8999999999999999,
 0.9999999999999999,
 1.0999999999999999,
 1.1999999999999997,
 1.2999999999999998,
 1.4,
 1.4999999999999996,
 1.5999999999999996,
 1.6999999999999997,
 1.7999999999999998,
 1.8999999999999995,
 1.9999999999999996,
 2.0999999999999996,
 2.1999999999999997,
 2.2999999999999994,
 2.3999999999999995,
 2.4999999999999996,
 2.599999999999999,
 2.6999999999999993,
 2.7999999999999994,
 2.8999999999999995,
 2.9999999999999996,
 3.099999999999999,
 3.1999999999999993,
 3.2999999999999994,
 3.399999999999999,
 3.499999999999999,
 3.599999999999999,
 3.6999999999999993,
 3.7999999999999994,
 3.899999999999999,
 3.999999999999999,
 4.1,
 4.199999999999999,
 4.299999999999999,
 4.3999999999999995,
 4.499999999999999,
 4.6,
 4.699999999999999,
 4.799999999999999,
 4.8999999999999995,
 4.999999999999999,
 5.1,
 5.199999999999999,
 5.299999999999999,
 5.3999999999999995,
 5.499999999999999,
 5.6,
 5.699999999999999,
 5.799999999999999

In [6]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [7]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [12]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
arr=np.ones((3,4))

In [15]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [17]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [18]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [21]:
arr1=np.eye(5)

In [23]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
import pandas as pd

In [27]:
data=pd.DataFrame(arr1)

In [28]:
data

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [29]:
np.random.rand(2,3)

array([[0.05771292, 0.4711363 , 0.66868977],
       [0.12904314, 0.26852342, 0.41520285]])

In [32]:
np.random.randn(2,3)

array([[-0.03066981,  0.48439918,  1.11905598],
       [ 0.96053604,  0.61454529, -1.6892515 ]])

In [35]:
arr2=np.random.randint(1,5, (3,4))

In [36]:
arr2

array([[1, 3, 3, 3],
       [1, 2, 1, 3],
       [2, 2, 3, 4]])

In [37]:
arr2.reshape(6,2)

array([[1, 3],
       [3, 3],
       [1, 2],
       [1, 3],
       [2, 2],
       [3, 4]])

In [39]:
arr2.reshape(4,-2)

array([[1, 3, 3],
       [3, 1, 2],
       [1, 3, 2],
       [2, 3, 4]])

In [40]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[1]]],


         [[[3]]],


         [[[3]]]],



        [[[[3]]],


         [[[1]]],


         [[[2]]]]],




       [[[[[1]]],


         [[[3]]],


         [[[2]]]],



        [[[[2]]],


         [[[3]]],


         [[[4]]]]]])

In [41]:
arr3=np.random.randint(1,10,(5,6))

In [42]:
arr3

array([[2, 4, 7, 4, 4, 2],
       [6, 1, 8, 1, 6, 3],
       [3, 4, 6, 8, 4, 8],
       [9, 3, 7, 5, 6, 6],
       [6, 6, 5, 5, 7, 3]])

In [43]:
arr3>6

array([[False, False,  True, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False,  True],
       [ True, False,  True, False, False, False],
       [False, False, False, False,  True, False]])

In [45]:
arr3<5

array([[ True,  True, False,  True,  True,  True],
       [False,  True, False,  True, False,  True],
       [ True,  True, False, False,  True, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False,  True]])

In [46]:
arr3[arr3<5]

array([2, 4, 4, 4, 2, 1, 1, 3, 3, 4, 4, 3, 3])

In [48]:
arr3

array([[2, 4, 7, 4, 4, 2],
       [6, 1, 8, 1, 6, 3],
       [3, 4, 6, 8, 4, 8],
       [9, 3, 7, 5, 6, 6],
       [6, 6, 5, 5, 7, 3]])

In [58]:
arr3[0,[0,1]]

array([2, 4])

In [59]:
arr3[2:4 ,[2,3]]

array([[6, 8],
       [7, 5]])

In [54]:
arr4=np.random.randint(1,3, (3,3))
arr5=np.random.randint(1,3,(3,3))

In [55]:
arr4

array([[2, 2, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [56]:
arr5

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [57]:
arr4+arr5

array([[4, 4, 3],
       [3, 3, 2],
       [3, 4, 3]])

In [60]:
arr4-arr5

array([[ 0,  0,  1],
       [-1,  1,  0],
       [ 1,  0,  1]])

In [61]:
arr4*arr5

array([[4, 4, 2],
       [2, 2, 1],
       [2, 4, 2]])

In [62]:
arr4

array([[2, 2, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [63]:
arr5

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [64]:
arr4/arr5

array([[1. , 1. , 2. ],
       [0.5, 2. , 1. ],
       [2. , 1. , 2. ]])

In [65]:
arr4/0

/tmp/ipykernel_99/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [67]:
arr6=np.zeros((3,4))

In [68]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr6+7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [72]:
a=np.array([1,3,5,7])

In [73]:
arr+a

array([[2., 4., 6., 8.],
       [2., 4., 6., 8.],
       [2., 4., 6., 8.]])

In [74]:
b=np.array([[3,4,5]])

In [77]:
arr7=arr6+b.T

In [76]:
b.T

array([[3],
       [4],
       [5]])

In [78]:
np.sqrt(arr7)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [79]:
np.log10(arr7)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [80]:
np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [81]:
np.min(arr7)

3.0

In [82]:
np.max(arr7)

5.0