In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6,7,8,9]

In [3]:
arr=np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(arr)

numpy.ndarray

In [10]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a=np.array([[1,2,3],[4,5,6]])

In [12]:
a.ndim

2

In [16]:
mat=np.matrix(l)

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [20]:
arr[0]=100

In [21]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [24]:
b=np.copy(arr)

In [25]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [26]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [28]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [31]:
iterable=(i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('23 24 25',sep=' ')

array([23., 24., 25.])

In [37]:
np.fromstring('23,24,25',sep=',')

array([23., 24., 25.])

In [38]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.size

6

In [43]:
arr.size

9

In [44]:
a.dtype

dtype('int64')

In [45]:
arr.dtype

dtype('int64')